### ISSUE TITLE
Freeze During Upload Step in Data Processing Script

### ISSUE THREAD

**Issue by HyunjunA** [EpistasisLab/KRAGEN#62]
<img width="715" alt="image" src="https://github.com/EpistasisLab/KRAGEN/assets/39776968/56e13ac5-a530-4912-b2f0-39d5620a2a2d">

- Experiencing a Freeze at the Upload Stage

**Comment by HyunjunA** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff6e22d1b0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.74', port=8080): Max retries exceeded with url: /v1/.well-known/ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6e22d1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 650, in wait_for_weaviate
    requests.get(ready_url, headers=self._get_request_header()).raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.74', port=8080): Max retries exceeded with url: /v1/.well-known/ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6e22d1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/src/kragen.py", line 59, in <module>
    main()
  File "/usr/src/app/src/kragen.py", line 53, in main
    setup(input_csv_file)
  File "/usr/src/app/src/k_setup.py", line 64, in setup
    step['func']()
  File "/usr/src/app/src/upload.py", line 107, in upload
    process_directory(
  File "/usr/src/app/src/upload.py", line 96, in process_directory
    batch_load_csv(class_name, csv_filepath)
  File "/usr/src/app/src/upload.py", line 87, in batch_load_csv
    add_object(class_name, row)
  File "/usr/src/app/src/upload.py", line 65, in add_object
    get_client().batch.configure(batch_size=200)
  File "/usr/src/app/src/upload.py", line 23, in get_client
    weaviate_client = weaviate.Client(
  File "/usr/local/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 166, in __init__
    self.wait_for_weaviate(startup_period)
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 653, in wait_for_weaviate
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://192.168.1.74:8080 is wrong or Weaviate did not start up in the interval given in 'startup_period'.

**Comment by jay-m-dev** [comment]
Please add the following information:
**steps to reproduce**
**OS**

**Comment by HyunjunA** [comment]
I renamed the .env.sample file to .env, updated the OPENAI_API_KEY with my own API key, and set the WEAVIATE_URL to http://mylocalIP:8080. I configured .env files in both the Frontend and Backend folders of the KRAGEN_Dashboard and initialized the config.json in the Backend using config.json.sample. Lastly, I executed the command docker-compose run kragen setup test.csv on my Mac.

**Comment by jay-m-dev** [comment]
I've experienced freezing, but so far, only when the WEAVIATE_URL is set to the wrong IP address. I'll add logs on the setup process (to get a better reading on this) when I work on #61

**Comment by jay-m-dev** [comment]
Found a related issue in the Weaviate Client Connection (see [here](https://github.com/weaviate/weaviate-python-client/issues/753)).
Perhaps adding a `timeout_config` as explained [here](https://weaviate.io/developers/weaviate/client-libraries/python/python_v3) may work. Or we can also try using a different method to get a **client** as explained [here](https://weaviate.io/developers/weaviate/client-libraries/python).
Alternatively, we could just migrate to using the weaviate client v4 (issue #53). But resolving #53 may take some time, since the v4 API is very different from v3.
