### ISSUE TITLE
gui container exits with code 1

### ISSUE THREAD

**Issue by ielegante** [EpistasisLab/KRAGEN#83]
This is a fantastic project! Have read the docs. Been trying to run it locally.

**Describe the bug**
gui container exits with code 1.
`[+] Running 3/0
 ✔ Container kragen-weaviate-1  Running                                   0.0s
 ✔ Container kragen-server      Running                                   0.0s
 ✔ Container kragen-gui         Created                                   0.0s
Attaching to kragen-gui
kragen-gui  |
kragen-gui  | > sigma-demo@0.1.0 start
kragen-gui  | > BROWSER=none react-scripts start --verbose
kragen-gui  |
kragen-gui  | (node:26) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
kragen-gui  | (Use `node --trace-deprecation ...` to show where the warning was created)
kragen-gui  | (node:26) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
kragen-gui exited with code 1
`

**To Reproduce**
I've followed the instructions on the readme.md but encountered this error. Other fixes that I have tried are: i) changing node version / node image in the Dockerfile; ii) running npm install in the frontend directory (which starts up fine but expectedly does not connect); iii) running with the `BROWSER=none` option in `react-scripts start`; and iv) running `docker compose run --rm -it gui /bin/bash` which on occasion reveals this error:
```node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 176.
    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v20.12.2
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 177.
    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v20.12.2
```

**Expected behavior**
gui container starts up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

Happy to help diagnose / fix the bug!

**Comment by HyunjunA** [comment]
Thank you for sharing this GitHub issue and for your detailed explanation.

I noticed that you have encountered an error when running the GUI container, which exits with code 1. However, I would like to better understand how you created this issue so I can provide more accurate assistance. Could you please clarify the steps?
